In [118]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st
from scipy.stats import linregress
import numpy as np

# Research data files
UE = "Govt_Data/Unemployment.csv"

# Read the data 
UE_data = pd.read_csv(UE)   # Unemployment data for 2019 and 2020

In [119]:
# Display Unemployment dataframe for preview.
UE_data

,Month,Total,"Men, 20 years and over","Women, 20 years and over",16 to 19 years old,White,Black or African American,Asian,Hispanic or Latino
0,11/1/2000,3.9,3.4,3.4,13.0,3.5,7.3,NaN,6.0
1,12/1/2000,3.9,3.4,3.3,13.2,3.5,7.4,NaN,5.7
2,1/1/2001,4.2,3.6,3.6,13.8,3.6,8.2,NaN,5.8
3,2/1/2001,4.2,3.7,3.7,13.7,3.7,7.7,NaN,6.1
4,3/1/2001,4.3,3.8,3.6,13.8,3.7,8.3,NaN,6.2
...,...,...,...,...,...,...,...,...,...
236,7/1/2020,10.2,9.4,10.5,19.3,9.2,14.6,12.0,12.9
237,8/1/2020,8.4,8.0,8.4,16.1,7.3,13.0,10.7,10.5
238,9/1/2020,7.9,7.4,7.7,15.9,7.0,12.1,8.9,10.3
239,10/1/2020,6.9,6.7,6.5,13.9,6.0,10.8,7.6,8.8
240,11/1/2020,6.7,6.7,6.1,14.0,5.9,10.3,6.7,8.4

In [120]:
# Remove unnecessary columns from source dataframe
UE_data = UE_data.drop(['Men, 20 years and over','Women, 20 years and over','16 to 19 years old','White','Black or African American','Asian','Hispanic or Latino'],axis=1)

# Rename column
UE_data = UE_data.rename(columns={'Month': 'Date','Total':'Rate (%)'})

# Display Unemployment rate dataframe
UE_data

          Date  Rate (%)
0    11/1/2000       3.9
1    12/1/2000       3.9
2     1/1/2001       4.2
3     2/1/2001       4.2
4     3/1/2001       4.3
..         ...       ...
236   7/1/2020      10.2
237   8/1/2020       8.4
238   9/1/2020       7.9
239  10/1/2020       6.9
240  11/1/2020       6.7

[241 rows x 2 columns]

In [123]:
# Remove Unemployment data beyond the end of the 3Q 2020

UE_data.to_datetime()

UE_data["Date"].dt.strftime('%m-%Y') 

UE_data

AttributeError: 'DataFrame' object has no attribute 'to_datetime'

In [108]:
print(UE_data.dtypes)

#UE_data = UE_data.drop(UE_data[(UE_data.Date > '10/1/2020') | (UE_data.Date < '12/1/2018')].index) 
#UE_data = UE_data[(UE_data['Date'] >= UE_data.datetime(19, 'Jan')) & (UE_data['Date'] <= UE_data.datetime(20, 'Sep'))]
UE_data = UE_data[UE_data['Date'] <= '12/1/2018']
#UE_data = UE_data[UE_data['Date'] <= Oct-20]
UE_data

Date         object
Rate (%)    float64
dtype: object

Empty DataFrame
Columns: [Date, Rate (%)]
Index: []

In [97]:
# Historical points as markers
# Group by Date to create df for historical markers.
UEI = UE_data.groupby(['Date']).sum()

dates = ["2020-03-27","2020-05-27"]
def find_loc(UEI, dates):
    marks = []
    for date in dates:
        marks.append(UEI.index.get_loc(date))
    return marks

In [99]:
minvalue = UE_data.loc[UE_data['Rate (%)'].idxmin()]  # Min price for Y-axis
#print(minvalue)
maxvalue = UE_data.loc[UE_data['Rate (%)'].idxmax()]  # Max price for Y-axis
#print(maxvalue)

# Line chart selection
UE_data.plot.line(x='Date', y='Rate (%)', legend = False, rot=60, title="Unemployment Rate from 2019 to 2020",markevery=find_loc(UEI, dates), marker='s', markerfacecolor='red');

# Sets the y limits
plt.ylim(2000, 3800)

# Provides labels
plt.xlabel(" ")
plt.ylabel("Unemployment Rate (%)", fontsize=12)

# Format tick marks
plt.tick_params(axis='both', direction='out', length=6, width=2, labelcolor = 'black',colors='teal')

# Major grid lines
plt.grid(b=True, which='major', color='lightblue', alpha=0.6, linestyle='dashdot', lw=1.5)

# Minor grid lines
plt.minorticks_on()
plt.grid(b=True, which='minor', color='beige', alpha=0.8, ls='-', lw=1)

# Save the figure as .png
plt.savefig('Images/Unemployment_Rate.png')

plt.show(block=True)

KeyError: '2020-03-27'