In [3]:
# Dependencies and Setup

In [ ]:
%matplotlib inline
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st
#import numpy as np

# Study data files
mouse_metadata_path = "data/Mouse_metadata.csv"
study_results_path = "data/Study_results.csv"

# Read the mouse data and the study results
mouse_metadata = pd.read_csv(mouse_metadata_path)
study_results = pd.read_csv(study_results_path)

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st
import numpy as np

# Study data files
unemployment = "Unemployment.csv"

# Read the mouse data and the study results
unemployment_df = pd.read_csv(unemployment)
unemployment_df

,Month,Total,"Men, 20 years and over","Women, 20 years and over",16 to 19 years old,White,Black or African American,Asian,Hispanic or Latino
0,Nov-00,3.9,3.4,3.4,13.0,3.5,7.3,NaN,6.0
1,Dec-00,3.9,3.4,3.3,13.2,3.5,7.4,NaN,5.7
2,Jan-01,4.2,3.6,3.6,13.8,3.6,8.2,NaN,5.8
3,Feb-01,4.2,3.7,3.7,13.7,3.7,7.7,NaN,6.1
4,Mar-01,4.3,3.8,3.6,13.8,3.7,8.3,NaN,6.2
...,...,...,...,...,...,...,...,...,...
236,Jul-20,10.2,9.4,10.5,19.3,9.2,14.6,12.0,12.9
237,Aug-20,8.4,8.0,8.4,16.1,7.3,13.0,10.7,10.5
238,Sep-20,7.9,7.4,7.7,15.9,7.0,12.1,8.9,10.3
239,Oct-20,6.9,6.7,6.5,13.9,6.0,10.8,7.6,8.8
240,Nov-20,6.7,6.7,6.1,14.0,5.9,10.3,6.7,8.4

In [ ]:
# Historical points as markers
# Group by Date to create df for historical markers.
df1 = df.groupby(['Date']).sum()

dates = ["2020-03-27","2020-05-27"]   
def find_loc(df1, dates):
    marks = []
    for date in dates:
        marks.append(df1.index.get_loc(date))
    return marks

In [ ]:
minvalue = df.loc[df['Avg Price'].idxmin()]  # Min price for Y-axis
#print(minvalue)
maxvalue = df.loc[df['Avg Price'].idxmax()]  # Max price for Y-axis
#print(maxvalue)

# Line chart selection
df.plot.line(x='Date', y='Avg Price', legend = False, rot=60, title="Title",markevery=find_loc(SPI, dates), marker='s', markerfacecolor='red');

# Sets the y limits
plt.ylim(2000, 3800)

# Provides labels
plt.xlabel(" ")
plt.ylabel("S&P Index Price", fontsize=12)

# Format tick marks
plt.tick_params(axis='both', direction='out', length=6, width=2, labelcolor = 'black',colors='teal')

# Major grid lines
plt.grid(b=True, which='major', color='lightblue', alpha=0.6, linestyle='dashdot', lw=1.5)

# Minor grid lines
plt.minorticks_on()
plt.grid(b=True, which='minor', color='beige', alpha=0.8, ls='-', lw=1)

# Save the figure as .png
plt.savefig('Images/Title.png')

plt.show(block=True)